# Use the official PostgreSQL image a# Use the official PostgreSQL image as the base image
FROM postgres:13

# Set environment variables for PostgreSQL
ENV POSTGRES_USER=sivanand
ENV POSTGRES_PASSWORD=12345
ENV POSTGRES_DB=openflight_DB

# Expose the PostgreSQL port
EXPOSE 5432

